### ISSUE TITLE
Oh boi

### ISSUE THREAD

**Issue by ArjixWasTaken** [shashstormer/anime-downloader-v3#2]
This reminds me of the time I used to write python, such a horrible language.

## Why Python Sucks

Let's start with indentation errors. What the actual fuck? No sane programming language structures itself on tabs, you want clear blocks? You want an end, well fuck you! Better make sure it's all aligned well. Are you 4 layers down into indentation, better make sure that screen real estate is holding up, wouldn't want to cause you any fucking stupid problems or anything. Wanna use tabs? Sure, use tabs, prettiest things on earth, some spaces, why not, throw it all in, oh wait, I like either one but not both together. Your dirty friend doesn't know how to set up his vim (and it shouldn't damn well matter), :retab won't work because you've now created a horrible mess. Oh, wanna git clone some code, for sure, just make sure you use the exact same configuration, and please do follow the joke of a style guide, it's the only way our programs actually run. BECAUSE THEy ARE DEPENDANT ON STYLE WHAT THE FUCK. Semicolons are optional, lovely. Want to flatten an array, .flatten? Nooooo, gotta overload the + operator sum(fuck,+) this how disgusting is that. Want to unique a list? .uniq? Something like that? Noooo list(set(my_list)) are you kidding me?! Type conversion will solve all our issues. 100. most disguting syntax, and a loop just iterates through a range. Ohhh, backwards compatability? Nopeeeeee, wouldn't want that in a scripting language now would we, too bad our original design was so messed up we had to be so brave to basically rewrite the whole thing, not like anyone was using it or anything.... And holy crap the syntax, most ugly thing I've ever seen what on earth Curly braces noooooope, too easy and they have the gall to call this entire monster the "pythonist" way, must be . Want to overload default operators in your class, just what they look like right? Nooope, every single one has a godamn special name, let's take a look at the list right, couldn't make it simple or anything. Want a ternary, eh? Something simple two character ?: magic? No, fuck you, use res1,res2 or a assbackwards most confusing and ugly horrific res1 if condition else res 2, I mean what the actualy fuck is that? Oh and let's preface all our functions with a thousand _____ like the tears you cry when you try to make sure it's the correct number, oh and always make sure to pass in self, wouldn't want to have scope or get lost or anything nooooo.

Well you may ask? Surely python must have something good right? All those scientists must use it for a reason (and 90% of them write horrific code and have no clue about it by the way, as is unsurprising, hence the python). Well yeah, it has some nice libraries, but that's like saying it's a nice car because someone decided to build a fancy trailer for it. And it automatically freezes string literals, that's slightly convenient.

**Comment by shashstormer** [comment]
Well if people really gonna use it then i would optimise it ensure backward compatibility. (But who is going to use this with almost no extra options for customisation)
This is just a minimal implementation and was made for my personal use this was made when i was a novice and have not made any major changes to it since then.

**Comment by ArjixWasTaken** [comment]
Bro deleted his replies, darn

**Comment by shashstormer** [comment]
Never knew deleted a message comes ...
Going to delete this repo tommorow noon...

**Comment by ArjixWasTaken** [comment]
Bro are you ok?

I know that I was trolling, but still, that's an overreaction even from my standards.
My opinion should not matter to you, and yes I did think the code was horrendous, but I have written even worse code.

We all have been there, can't really shame anyone as this is a canon event. (spiderverse meme)

**Comment by shashstormer** [comment]
I dont want an issue with the message i deleted a comment so am deleting the repo

**Comment by ArjixWasTaken** [comment]
maybe hide comments instead of deleting them?

Also this is a copypasta, nobody would think bad of you for deleting comments.

**Comment by shashstormer** [comment]
I really dont care much about the code but one star is going to be lost but cant do anything...

**Comment by ArjixWasTaken** [comment]
Bruh, I feel bad now

**Comment by ArjixWasTaken** [comment]
Look, I have a lot of repositories, half of them are from my noobie days and have worse code than yours.
It's really not the end of the world.

**Comment by shashstormer** [comment]
There is no hide code option
At least not on phone
My laptop is broken since 1 month and cant see desktop options so 
Just gonna delete the repo

**Comment by shashstormer** [comment]
I never said my code was an issue i don't actually mind deleting the repo and re uploading it with same thing just want the deleted a comment to go

**Comment by shashstormer** [comment]
Tbh i wanted to delete this repo and the first version (second one also) anime-downloader (see my repos)
Put this as anime-downloader 

But had left this as it had one start 

Now i have deleted a comment, it feels like a black mark (for me atleast) so just gonna delete this repo as this overweighs one star
